name: PR Validation

on:
  pull_request:
    branches: [ develop ]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Validate PR
        run: echo "Pull request to develop branch is valid!"
